# Generated by Django 5.0.1 on 2024-02-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
